framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async
            App\Message\RecheckAssetMetadataMessage: async
            App\Message\AITaggingMessage: async
            App\Message\CompletelyDeleteAssetMessage: async
            App\Message\AssetCollectionUpdatedMessage: async
            App\Message\CategoryUpdatedMessage: async
            App\Message\CategoryCollectionCountUpdateMessage: async
            App\Message\Filesize\UpdateUploadSizesMessage: async
            App\Message\Filesize\UpdateUserUploadSizeMessage: async
            App\Message\Filesize\UpdateMembershipUploadSizeMessage: async
            App\Message\Filesize\UpdateWorkspaceUploadSizeMessage: async
            App\Message\UpdateAssetVisibilityMessage: async

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
